feat: Make tariff and condition links configurable
camptocamp/geoshop-front pull request #64
Opened 2024-11-27 14:45 UTC by lanseg

Now links to the pdf/docs to the tariff information and usage conditions are configurable with config.json

2025-01-08 14:36 UTC, jwkaltz commented
@lanseg is this pull request still relevant, I think the problem has been solved in a different manner?

2025-01-10 06:45 UTC, jwkaltz requested changes
Thanks @lanseg the pull request looks clear to me, but we also need entries in the german language xlf, or not?

2025-01-10 12:55 UTC, lanseg commented
> ?

German translation is already there - in the messages.de, line 151 and 159

2025-01-10 12:58 UTC, jwkaltz approved these changes

2025-01-10 13:00 UTC, merged